// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFEQOY2zbp7ndotmk8ui6ctb6OYy9Psg',
    appId: '1:330929272260:web:0ea34dadb3accd47c92091',
    messagingSenderId: '330929272260',
    projectId: 'iot-app-4e4f2',
    databaseURL: 'https://iot-app-4e4f2-default-rtdb.firebaseio.com',
    authDomain: 'iot-app-4e4f2.firebaseapp.com',
    storageBucket: 'iot-app-4e4f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlioHDfyzJdlG2-ZzDoIVSLrknCkYyumw',
    appId: '1:330929272260:android:0dd5d5e29f443d47c92091',
    messagingSenderId: '330929272260',
    projectId: 'iot-app-4e4f2',
    databaseURL: 'https://iot-app-4e4f2-default-rtdb.firebaseio.com',
    storageBucket: 'iot-app-4e4f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo3K1jUV_E3HzVToFtpz4c84wkP2X-tLk',
    appId: '1:330929272260:ios:a64d8bd8c32e54b1c92091',
    messagingSenderId: '330929272260',
    projectId: 'iot-app-4e4f2',
    databaseURL: 'https://iot-app-4e4f2-default-rtdb.firebaseio.com',
    storageBucket: 'iot-app-4e4f2.appspot.com',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo3K1jUV_E3HzVToFtpz4c84wkP2X-tLk',
    appId: '1:330929272260:ios:c460cf657eeb1314c92091',
    messagingSenderId: '330929272260',
    projectId: 'iot-app-4e4f2',
    storageBucket: 'iot-app-4e4f2.appspot.com',
    iosBundleId: 'com.example.iotApp.RunnerTests',
  );
}
